#!/bin/bash
# Pre-commit hook: Prevent committing auto-generated files
# These should only be generated at build/deploy time by generate_site.py

set -e

# Files that must never be committed (always 100% generated)
FORBIDDEN_FILES=(
  "docs/_sidebar.md"
  "docs/index.html"
  "docs/404.html"
  "docs/sitemap.xml"
)

# Check for forbidden files in staged changes
for file in "${FORBIDDEN_FILES[@]}"; do
  if git diff --cached --name-only | grep -q "^$file$"; then
    echo "ERROR: Generated file '$file' would be committed."
    echo "This file is auto-generated by scripts/generate_site.py and should not be tracked."
    echo ""
    echo "To fix:"
    echo "  git reset HEAD '$file'"
    echo "  git checkout '$file'"
    exit 1
  fi
done

# Check for docs/books/*/index.html (generated per-book pages)
if git diff --cached --name-only | grep -q "^docs/books/.*/index.html$"; then
  echo "ERROR: Generated book page(s) would be committed."
  echo "Book pages in docs/books/*/index.html are auto-generated and should not be tracked."
  echo ""
  echo "To fix:"
  echo "  git reset HEAD 'docs/books/*/index.html'"
  echo "  git checkout 'docs/books/*/index.html'"
  exit 1
fi

# Check docs/README.md: it should only have hand-written content outside the markers
if git diff --cached --name-only | grep -q "^docs/README.md$"; then
  # Get the staged version
  staged_content=$(git show :docs/README.md)

  # Check if generated content exists between markers
  if echo "$staged_content" | grep -A 100 "<!-- BEGIN GENERATED CATALOG -->" | grep -B 100 "<!-- END GENERATED CATALOG -->" | grep -qv "<!-- \(BEGIN\|END\) GENERATED CATALOG -->"; then
    echo "ERROR: docs/README.md contains auto-generated catalog content."
    echo "Only the introduction (before BEGIN GENERATED CATALOG) and any footer"
    echo "(after END GENERATED CATALOG) should be committed."
    echo ""
    echo "To fix:"
    echo "  1. Run: python3 scripts/generate_site.py"
    echo "  2. Edit docs/README.md to remove content between markers"
    echo "  3. Stage only the hand-written parts"
    exit 1
  fi
fi

exit 0
